name: CI

on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - ".gitignore"
  pull_request:

concurrency:
  group: build-and-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Check formatting & linting
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Set up Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: 6.3.0

      - name: Check formatting & linting
        run: ./lint.sh

  build:
    name: Build and test (${{ matrix.target }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-24.04, target: linux-x64 }
          - { os: macos-26,     target: macos-arm64 }
          - { os: windows-2025, target: windows-x64 }

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - name: Set up Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: 6.3.0

      - name: Build and test
        run: swift test --verbose
